"""Markdown diagnostics report."""
from __future__ import annotations

from collections import Counter
from pathlib import Path

from ..diagnostics import CODES
from ..schema import Project


def write_report(project: Project, path: str | Path) -> Path:
    s = project.summary
    lines = [
        f"# C2B extraction report: {project.drawing.file}",
        "",
        f"Generated by {project.generator}, schema {project.schema_version}.",
        "",
        f"Units: {project.drawing.unit_name} (scale {project.drawing.unit_scale_to_mm} to mm, source {project.drawing.unit_source}, confidence {project.drawing.unit_confidence}).",
        "",
        "## Summary",
        "",
        "| Item | Count |", "|---|---|",
        f"| Floors | {s.floors} |", f"| Grids | {s.grids} |", f"| Columns | {s.columns} |", f"| Beams | {s.beams} |",
        f"| Slabs (tags/outlines) | {s.slabs} |", f"| Footings | {s.footings} |", f"| Openings | {s.openings} |",
        f"| Walls | {s.walls} |", f"| Schedules | {s.schedules} |", f"| Unassigned tags | {s.tags_unassigned} |",
        f"| Errors | {s.errors} |", f"| Warnings | {s.warnings} |", f"| Infos | {s.infos} |",
        "",
        "## Floors",
        "",
        "| Id | Name | Source | Origin (drawing mm) | Columns | Beams | Slabs | Footings | Grids | Default beam depth | Default slab thk |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for f in project.floors:
        c = f.counts
        lines.append(f"| {f.id} | {f.name} | {f.name_source} | ({f.origin.x:.0f}, {f.origin.y:.0f}) | {c.get('columns', 0)} | {c.get('beams', 0)} | {c.get('slabs', 0)} | {c.get('footings', 0)} | {c.get('grids', 0)} | {f.default_beam_depth_mm or ''} | {f.default_slab_thickness_mm or ''} |")
    lines += ["", "## Diagnostics by code", "", "| Severity | Code | Count | Meaning |", "|---|---|---|---|"]
    counts = Counter((d.severity, d.code) for d in project.diagnostics)
    order = {"ERROR": 0, "WARNING": 1, "INFO": 2}
    for (sev, code), n in sorted(counts.items(), key=lambda kv: (order[kv[0][0]], -kv[1])):
        lines.append(f"| {sev} | {code} | {n} | {CODES.get(code, '')} |")
    lines += ["", "## Diagnostics (first 400)", ""]
    for d in sorted(project.diagnostics, key=lambda d: (order[d.severity], d.floor_id or "", d.code))[:400]:
        loc = f" @({d.location.x:.0f},{d.location.y:.0f})" if d.location else ""
        ctx = " ".join(x for x in [f"[{d.floor_id}]" if d.floor_id else "", f"layer={d.layer}" if d.layer else "", f"handle={d.handle}" if d.handle else "", f"elem={d.element_id}" if d.element_id else ""] if x)
        lines.append(f"- **{d.severity}** `{d.code}` {ctx}{loc}: {d.message}")
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return Path(path)
